/// <filename>
///     CoinCreated.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Events
{
  public class CoinCreated : ZES.Infrastructure.Domain.Event
  {
    public CoinCreated() 
    {
    }  
    public string Name
    {
       get; 
       set;
    }  
    public string Ticker
    {
       get; 
       set;
    }  
    public CoinCreated(string name, string ticker) 
    {
      Name = name; 
      Ticker = ticker;
    }
  }
}

