/// <filename>
///     CoinMined.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Events
{
  public class CoinMined : ZES.Infrastructure.Domain.Event
  {
    public CoinMined() 
    {
    }  
    public Core.Quantity MineQuantity
    {
       get; 
       set;
    }  
    public int BlockHeight
    {
       get; 
       set;
    }  
    public CoinMined(Core.Quantity mineQuantity, int blockHeight) 
    {
      MineQuantity = mineQuantity; 
      BlockHeight = blockHeight;
    }
  }
}

