/// <filename>
///     WalletBalanceChanged.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Events
{
  public class WalletBalanceChanged : ZES.Infrastructure.Domain.Event
  {
    public WalletBalanceChanged() 
    {
    }  
    public double Delta
    {
       get; 
       set;
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public WalletBalanceChanged(double delta, string txId) 
    {
      Delta = delta; 
      TxId = txId;
    }
  }
}

