/// <filename>
///     WalletCreated.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Events
{
  public class WalletCreated : ZES.Infrastructure.Domain.Event
  {
    public WalletCreated() 
    {
    }  
    public string Address
    {
       get; 
       set;
    }  
    public WalletCreated(string address) 
    {
      Address = address;
    }
  }
}

