/// <filename>
///     AssetPairRegistered.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Events
{
  public class AssetPairRegistered : ZES.Infrastructure.Domain.Event
  {
    public AssetPairRegistered() 
    {
    }  
    public string Fordom
    {
       get; 
       set;
    }  
    public Asset ForAsset
    {
       get; 
       set;
    }  
    public Asset DomAsset
    {
       get; 
       set;
    }  
    public AssetPairRegistered(string fordom, Asset forAsset, Asset domAsset) 
    {
      Fordom = fordom; 
      ForAsset = forAsset; 
      DomAsset = domAsset;
    }
  }
}

