/// <filename>
///     QuoteAdded.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Events
{
  public class QuoteAdded : ZES.Infrastructure.Domain.Event
  {
    public QuoteAdded() 
    {
    }  
    public NodaTime.Instant Date
    {
       get; 
       set;
    }  
    public double Close
    {
       get; 
       set;
    }  
    public double Open
    {
       get; 
       set;
    }  
    public double Low
    {
       get; 
       set;
    }  
    public double High
    {
       get; 
       set;
    }  
    public QuoteAdded(NodaTime.Instant date, double close, double open, double low, double high) 
    {
      Date = date; 
      Close = close; 
      Open = open; 
      Low = low; 
      High = high;
    }
  }
}

