/// <filename>
///     QuoteUrlAdded.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Events
{
  public class QuoteUrlAdded : ZES.Infrastructure.Domain.Event
  {
    public QuoteUrlAdded() 
    {
    }  
    public string Url
    {
       get; 
       set;
    }  
    public QuoteUrlAdded(string url) 
    {
      Url = url;
    }
  }
}

