/// <filename>
///     TransactionQuoteAdded.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Events
{
  public class TransactionQuoteAdded : ZES.Infrastructure.Domain.Event
  {
    public TransactionQuoteAdded() 
    {
    }  
    public Quantity Quantity
    {
       get; 
       set;
    }  
    public TransactionQuoteAdded(Quantity quantity) 
    {
      Quantity = quantity;
    }
  }
}

