/// <filename>
///     TransactionRecorded.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Events
{
  public class TransactionRecorded : ZES.Infrastructure.Domain.Event
  {
    public TransactionRecorded() 
    {
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public Quantity Quantity
    {
       get; 
       set;
    }  
    public Transaction.TransactionType TransactionType
    {
       get; 
       set;
    }  
    public string Comment
    {
       get; 
       set;
    }  
    public TransactionRecorded(string txId, Quantity quantity, Transaction.TransactionType transactionType, string comment) 
    {
      TxId = txId; 
      Quantity = quantity; 
      TransactionType = transactionType; 
      Comment = comment;
    }
  }
}

