/// <filename>
///     ChangeWalletBalanceHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Coins.Commands
{
  public class ChangeWalletBalanceHandler : ZES.Infrastructure.Domain.CommandHandlerBase<ChangeWalletBalance, Wallet>
  {
    public ChangeWalletBalanceHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Wallet wallet, ChangeWalletBalance command)
    {
      wallet.ApplyDelta(command.Delta, command.TxId);
    }
  }
}

