/// <filename>
///     ChangeWalletBalance.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Commands
{
  public class ChangeWalletBalance : ZES.Infrastructure.Domain.Command
  {
    public ChangeWalletBalance() 
    {
    }  
    public string Address
    {
       get; 
       set;
    }  
    public Core.Quantity Delta
    {
       get; 
       set;
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Address;
      }
    }  
    public ChangeWalletBalance(string address, Core.Quantity delta, string txId) 
    {
      Address = address; 
      Delta = delta; 
      TxId = txId;
    }
  }
}

