/// <filename>
///     CreateCoinHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Coins.Commands
{
  public class CreateCoinHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateCoin, Coin>
  {
    public CreateCoinHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Coin Create (CreateCoin command)
    {
      return new Coin(command.Name, command.Ticker);
    }
  }
}

