/// <filename>
///     CreateCoinHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Commands
{
  public class CreateCoinHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateCoin, Coin>
  {
    public CreateCoinHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Coin Create (CreateCoin command)
    {
      return new Coin(command.Name, command.Ticker);
    }
  }
}

