/// <filename>
///     CreateWallet.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Commands
{
  public class CreateWallet : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public CreateWallet() 
    {
    }  
    public string Address
    {
       get; 
       set;
    }  
    public string Coin
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Address;
      }
    }  
    public CreateWallet(string address, string coin) 
    {
      Address = address; 
      Coin = coin;
    }
  }
}

