/// <filename>
///     CreateCoin.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Commands
{
  public class CreateCoin : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public CreateCoin() 
    {
    }  
    public string Name
    {
       get; 
       set;
    }  
    public string Ticker
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Name;
      }
    }  
    public CreateCoin(string name, string ticker) 
    {
      Name = name; 
      Ticker = ticker;
    }
  }
}

