/// <filename>
///     MineCoinHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Commands
{
  public class MineCoinHandler : ZES.Infrastructure.Domain.CommandHandlerBase<MineCoin, Wallet>
  {
    public MineCoinHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Wallet wallet, MineCoin command)
    {
      wallet.MineCoin(command.MineQuantity, command.BlockHeight);
    }
  }
}

