/// <filename>
///     MineCoinHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Coins.Commands
{
  public class MineCoinHandler : ZES.Infrastructure.Domain.CommandHandlerBase<MineCoin, Wallet>
  {
    public MineCoinHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Wallet wallet, MineCoin command)
    {
      wallet.MineCoin(command.MineQuantity, command.BlockHash);
    }
  }
}

