/// <filename>
///     MineCoin.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Commands
{
  public class MineCoin : ZES.Infrastructure.Domain.Command
  {
    public MineCoin() 
    {
    }  
    public string Address
    {
       get; 
       set;
    }  
    public double MineQuantity
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Address;
      }
    }  
    public MineCoin(string address, double mineQuantity) 
    {
      Address = address; 
      MineQuantity = mineQuantity;
    }
  }
}

