/// <filename>
///     TransferCoinsHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Coins.Commands
{
  public class TransferCoinsHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<TransferCoins, Transfer>
  {
    public TransferCoinsHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Transfer Create (TransferCoins command)
    {
      return new Transfer(command.TxId, command.FromAddress, command.ToAddress, command.Quantity, command.Fee);
    }
  }
}

