/// <filename>
///     TransferCoinsHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Commands
{
  public class TransferCoinsHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<TransferCoins, Transaction>
  {
    public TransferCoinsHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Transaction Create (TransferCoins command)
    {
      return new Transaction(command.TxId, command.FromAddress, command.ToAddress, command.Quantity, command.Fee);
    }
  }
}

