/// <filename>
///     AccountCreated.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Events
{
  public class AccountCreated : ZES.Infrastructure.Domain.Event
  {
    public AccountCreated() 
    {
    }  
    public string Name
    {
       get; 
       set;
    }  
    public AccountType Type
    {
       get; 
       set;
    }  
    public AccountCreated(string name, AccountType type) 
    {
      Name = name; 
      Type = type;
    }
  }
}

