/// <filename>
///     AssetDeposited.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Events
{
  public class AssetDeposited : ZES.Infrastructure.Domain.Event
  {
    public AssetDeposited() 
    {
    }  
    public string AssetId
    {
       get; 
       set;
    }  
    public double Quantity
    {
       get; 
       set;
    }  
    public AssetDeposited(string assetId, double quantity) 
    {
      AssetId = assetId; 
      Quantity = quantity;
    }
  }
}

