/// <filename>
///     TransactionAdded.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Events
{
  public class TransactionAdded : ZES.Infrastructure.Domain.Event
  {
    public TransactionAdded() 
    {
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public TransactionAdded(string txId) 
    {
      TxId = txId;
    }
  }
}

