/// <filename>
///     TransferStarted.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Events
{
  public class TransferStarted : ZES.Infrastructure.Domain.Event
  {
    public TransferStarted() 
    {
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public string FromAccount
    {
       get; 
       set;
    }  
    public string ToAccount
    {
       get; 
       set;
    }  
    public Core.Quantity Amount
    {
       get; 
       set;
    }  
    public TransferStarted(string txId, string fromAccount, string toAccount, Core.Quantity amount) 
    {
      TxId = txId; 
      FromAccount = fromAccount; 
      ToAccount = toAccount; 
      Amount = amount;
    }
  }
}

