/// <filename>
///     TransferCompleted.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Events
{
  public class TransferCompleted : ZES.Infrastructure.Domain.Event
  {
    public TransferCompleted() 
    {
    }
  }
}

