/// <filename>
///     AddQuote.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Commands
{
  public class AddQuote : ZES.Infrastructure.Domain.Command
  {
    public AddQuote() 
    {
    }  
    public string Fordom
    {
       get; 
       set;
    }  
    public NodaTime.Instant Date
    {
       get; 
       set;
    }  
    public double Close
    {
       get; 
       set;
    }  
    public double Open
    {
       get; 
       set;
    }  
    public double Low
    {
       get; 
       set;
    }  
    public double High
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Fordom;
      }
    }  
    public AddQuote(string fordom, NodaTime.Instant date, double close, double open = 0, double low = 0, double high = 0) 
    {
      Fordom = fordom; 
      Date = date; 
      Close = close; 
      Open = open; 
      Low = low; 
      High = high;
    }
  }
}

