/// <filename>
///     AddQuoteUrlHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Commands
{
  public class AddQuoteUrlHandler : ZES.Infrastructure.Domain.CommandHandlerBase<AddQuoteUrl, AssetPair>
  {
    public AddQuoteUrlHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (AssetPair assetPair, AddQuoteUrl command)
    {
      assetPair.AddUrl(command.Url);
    }
  }
}

