/// <filename>
///     AddQuoteHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Core.Commands
{
  public class AddQuoteHandler : ZES.Infrastructure.Domain.CommandHandlerBase<AddQuote, AssetPair>
  {
    public AddQuoteHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (AssetPair assetPair, AddQuote command)
    {
      assetPair.AddQuote(command.Date, command.Close, command.Open, command.Low, command.High);
    }
  }
}

