/// <filename>
///     AddTransactionQuote.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Commands
{
  public class AddTransactionQuote : ZES.Infrastructure.Domain.Command
  {
    public AddTransactionQuote() 
    {
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public Quantity Quantity
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return TxId;
      }
    }  
    public AddTransactionQuote(string txId, Quantity quantity) 
    {
      TxId = txId; 
      Quantity = quantity;
    }
  }
}

