/// <filename>
///     RecordTransactionHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Core.Commands
{
  public class CreateTransactionHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateTransaction, Transaction>
  {
    public CreateTransactionHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Transaction Create (CreateTransaction command)
    {
      return new Transaction(command.TxId, command.Amount, command.TransactionType, command.Comment, command.AssetId);
    }
  }
}

