/// <filename>
///     RecordTransactionHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Core.Commands
{
  public class RecordTransactionHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<RecordTransaction, Transaction>
  {
    public RecordTransactionHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Transaction Create (RecordTransaction command)
    {
      return new Transaction(command.TxId, command.Amount, command.TransactionType, command.Comment);
    }
  }
}

