/// <filename>
///     RecordTransaction.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Commands
{
  public class RecordTransaction : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public RecordTransaction() 
    {
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public Quantity Amount
    {
       get; 
       set;
    }  
    public Transaction.TransactionType TransactionType
    {
       get; 
       set;
    }  
    public string Comment
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return TxId;
      }
    }  
    public RecordTransaction(string txId, Quantity amount, Transaction.TransactionType transactionType, string comment) 
    {
      TxId = txId; 
      Amount = amount; 
      TransactionType = transactionType; 
      Comment = comment;
    }
  }
}

