/// <filename>
///     UpdateTransactionDetailsHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Commands
{
  public class UpdateTransactionDetailsHandler : ZES.Infrastructure.Domain.CommandHandlerBase<UpdateTransactionDetails, Transaction>
  {
    public UpdateTransactionDetailsHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Transaction transaction, UpdateTransactionDetails command)
    {
      transaction.UpdateDetails(command.TransactionType, command.Comment);
    }
  }
}

