/// <filename>
///     UpdateQuote.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.Net;

namespace Chronos.Core.Commands
{
  public class UpdateQuote : ZES.Infrastructure.Domain.Command
  {
    public UpdateQuote() 
    {
    } 
    
    public UpdateQuote(string fordom) 
    {
      Fordom = fordom;
    }

    public string Fordom
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Fordom;
      }
    }  
  }

  public class UpdateQuote<T> : UpdateQuote
    where T : class, IJsonResult
  {
    public UpdateQuote()
    { }
    
    public UpdateQuote(string fordom) 
      : base(fordom) 
    { }
  }
}

