/// <filename>
///     UpdateTransactionDetails.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Commands
{
  public class UpdateTransactionDetails : ZES.Infrastructure.Domain.Command
  {
    public UpdateTransactionDetails() 
    {
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public Transaction.TransactionType TransactionType
    {
       get; 
       set;
    }  
    public string Comment
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return TxId;
      }
    }  
    public UpdateTransactionDetails(string txId, Transaction.TransactionType transactionType, string comment) 
    {
      TxId = txId; 
      TransactionType = transactionType; 
      Comment = comment;
    }
  }
}

