/// <filename>
///     Hashflare.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare
{
  public class Hashflare : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public Hashflare() 
    {
      Register<Chronos.Hashflare.Events.HashflareRegistered>(ApplyEvent); 
      Register<Chronos.Hashflare.Events.CoinMined>(ApplyEvent);
    }  
    public Hashflare(string id, string username) : this() 
    {
      Id = id; 
      When(new Chronos.Hashflare.Events.HashflareRegistered(username));
    }  
    public string Username
    {
       get; 
       set;
    }  
    public void AddAmountMined (string type, double quantity)
    {
      When(new Chronos.Hashflare.Events.CoinMined(type, quantity));
    }  
    private void ApplyEvent (Chronos.Hashflare.Events.HashflareRegistered e)
    {
      Username = e.Username;
    }  
    private void ApplyEvent (Chronos.Hashflare.Events.CoinMined e)
    {
    }
  }
}

