/// <filename>
///     Coin.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins
{
  public class Coin : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public Coin() 
    {
      Register<Chronos.Coins.Events.CoinCreated>(ApplyEvent);
    }  
    public Coin(string name, string ticker) : this() 
    {
      When(new Chronos.Coins.Events.CoinCreated(name, ticker));
    }  
    private void ApplyEvent (Chronos.Coins.Events.CoinCreated e)
    {
      Id = e.Name;
    }
  }
}

