/// <filename>
///     Coin.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins
{
  public sealed class Coin : ZES.Infrastructure.Domain.AggregateRoot
  {
    public Coin() 
    {
      Register<Chronos.Coins.Events.CoinCreated>(ApplyEvent);
    }  
    public Coin(string name, string ticker) : this() 
    {
      When(new Chronos.Coins.Events.CoinCreated(name, ticker));
    }  
    public string Name
    {
      get; 
      set;
    }  
    public string Ticker
    {
      get; 
      set;
    }  
    private void ApplyEvent (Chronos.Coins.Events.CoinCreated e)
    {
      Id = e.Name;
      Name = e.Name;
      Ticker = e.Ticker;
    }
  }
}

