/// <filename>
///     Transaction.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins
{
  public class Transaction : ZES.Infrastructure.Domain.EventSourced, ZES.Interfaces.Domain.IAggregate
  {
    public Transaction() 
    {
      Register<Chronos.Coins.Events.CoinsTransferred>(ApplyEvent);
    }  
    public Transaction(string txId, string fromAddress, string toAddress, double quantity, double fee) : this() 
    {
      When(new Chronos.Coins.Events.CoinsTransferred(txId, fromAddress, toAddress, quantity, fee));
    }  
    private void ApplyEvent (Chronos.Coins.Events.CoinsTransferred e)
    {
      Id = e.TxId;
    }
  }
}

