/// <filename>
///     Wallet.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins
{
  public sealed class Wallet : ZES.Infrastructure.Domain.AggregateRoot
  {
    public Wallet() 
    {
      Register<Chronos.Coins.Events.WalletCreated>(ApplyEvent); 
      Register<Chronos.Coins.Events.WalletBalanceChanged>(ApplyEvent); 
      Register<Chronos.Coins.Events.CoinMined>(ApplyEvent);
    }  
    public Wallet(string address) : this() 
    {
      When(new Chronos.Coins.Events.WalletCreated(address));
    }  
    public void ApplyDelta (double delta, string txId)
    {
      When(new Chronos.Coins.Events.WalletBalanceChanged(delta, txId));
    }  
    public void MineCoin (double mineQuantity)
    {
      When(new Chronos.Coins.Events.CoinMined(mineQuantity));
      When(new Chronos.Coins.Events.WalletBalanceChanged(mineQuantity, string.Empty));
    }  
    private void ApplyEvent (Chronos.Coins.Events.WalletCreated e)
    {
      Id = e.Address;
    }  
    private void ApplyEvent (Chronos.Coins.Events.WalletBalanceChanged e)
    {
    }  
    private void ApplyEvent (Chronos.Coins.Events.CoinMined e)
    {
    }
  }
}

