/// <filename>
///     Transfer.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts
{
  public sealed class Transfer : ZES.Infrastructure.Domain.AggregateRoot
  {
    public Transfer() 
    {
      Register<Chronos.Accounts.Events.TransferStarted>(ApplyEvent);
    }  
    public Transfer(string txId, string fromAccount, string toAccount, Core.Quantity amount) : this() 
    {
      When(new Chronos.Accounts.Events.TransferStarted(txId, fromAccount, toAccount, amount));
    }  
    private void ApplyEvent (Chronos.Accounts.Events.TransferStarted e)
    {
      Id = e.TxId;
    }
  }
}

