/// <filename>
///     AddTransaction.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class AddTransaction : ZES.Infrastructure.Domain.Command
  {
    public AddTransaction() 
    {
    }  
    public string Name
    {
       get; 
       set;
    }  
    public string TxId
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Name;
      }
    }  
    public AddTransaction(string name, string txId) 
    {
      Name = name; 
      TxId = txId;
    }
  }
}

