/// <filename>
///     AddTransactionHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class AddTransactionHandler : ZES.Infrastructure.Domain.CommandHandlerBase<AddTransaction, Account>
  {
    public AddTransactionHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Account account, AddTransaction command)
    {
      account.AddTransaction(command.TxId);
    }
  }
}

