/// <filename>
///     CreateAccount.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class CreateAccount : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public CreateAccount() 
    {
    }  
    public Account.Type Type
    {
       get; 
       set;
    }  
    public CreateAccount(string target, Account.Type type) : base(target) 
    {
      Type = type;
    }
  }
}

