/// <filename>
///     CreateAccountHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class CreateAccountHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateAccount, Account>
  {
    public CreateAccountHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Account Create (CreateAccount command)
    {
      return new Account(command.Target, command.Type);
    }
  }
}

