/// <filename>
///     CreateAccountHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Accounts.Commands
{
  public class CreateAccountHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateAccount, Account>
  {
    public CreateAccountHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Account Create (CreateAccount command)
    {
      return new Account(command.Name, command.Type);
    }
  }
}

