/// <filename>
///     CreateAccount.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class CreateAccount : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public CreateAccount() 
    {
    }  
    public string Name
    {
       get;
    }  
    public Account.Type Type
    {
       get;
    }  
    public override string Target
    {
       get
      {
        return Name;
      }
    }  
    public CreateAccount(string name, Account.Type type) 
    {
      Name = name; 
      Type = type;
    }
  }
}

