/// <filename>
///     DepositAssetHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class DepositAssetHandler : ZES.Infrastructure.Domain.CommandHandlerBase<DepositAsset, Account>
  {
    public DepositAssetHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Account account, DepositAsset command)
    {
      account.DepositAsset(command.Quantity);
    }
  }
}

