/// <filename>
///     DepositAsset.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class DepositAsset : ZES.Infrastructure.Domain.Command
  {
    public DepositAsset() 
    {
    }  
    public string Name
    {
       get; 
       set;
    }  
    public Chronos.Core.Quantity Quantity
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return Name;
      }
    }  
    public DepositAsset(string name, Chronos.Core.Quantity quantity) 
    {
      Name = name; 
      Quantity = quantity;
    }
  }
}

