/// <filename>
///     DepositAsset.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Commands
{
  public class DepositAsset : ZES.Infrastructure.Domain.Command
  {
    public DepositAsset() 
    {
    }  
    public string Name
    {
       get;
    }  
    public string AssetId
    {
       get;
    }  
    public double Quantity
    {
       get;
    }  
    public override string Target
    {
       get
      {
        return Name;
      }
    }  
    public DepositAsset(string name, string assetId, double quantity) 
    {
      Name = name; 
      AssetId = assetId; 
      Quantity = quantity;
    }
  }
}

