/// <filename>
///     CoinMinedByContract.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Events
{
  public class CoinMinedByContract : ZES.Infrastructure.Domain.Event
  {
    public CoinMinedByContract() 
    {
    }  
    public string Type
    {
       get; 
       set;
    }  
    public double Quantity
    {
       get; 
       set;
    }  
    public CoinMinedByContract(string type, double quantity) 
    {
      Type = type; 
      Quantity = quantity;
    }
  }
}

