/// <filename>
///     ContractExpired.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Events
{
  public class ContractExpired : ZES.Infrastructure.Domain.Event
  {
    public ContractExpired() 
    {
    }
  }
}

