/// <filename>
///     ContractCreated.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Events
{
  public class ContractCreated : ZES.Infrastructure.Domain.Event
  {
    public ContractCreated() 
    {
    }  
    public string ContractId
    {
       get; 
       set;
    }  
    public string Type
    {
       get; 
       set;
    }  
    public int Quantity
    {
       get; 
       set;
    }  
    public double Total
    {
       get; 
       set;
    }  
    public ContractCreated(string contractId, string type, int quantity, double total) 
    {
      ContractId = contractId; 
      Type = type; 
      Quantity = quantity; 
      Total = total;
    }
  }
}

