/// <filename>
///     HashflareRegistered.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Events
{
  public class HashflareRegistered : ZES.Infrastructure.Domain.Event
  {
    public HashflareRegistered() 
    {
    }  
    public string Username
    {
       get; 
       set;
    }  
    public HashflareRegistered(string username) 
    {
      Username = username;
    }
  }
}

