/// <filename>
///     AddMinedCoinToContractHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Hashflare.Commands
{
  public class AddMinedCoinToContractHandler : ZES.Infrastructure.Domain.CommandHandlerBase<AddMinedCoinToContract, Contract>
  {
    public AddMinedCoinToContractHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Contract contract, AddMinedCoinToContract command)
    {
      contract.AddAmountMined(command.Type, command.Quantity);
    }
  }
}

