/// <filename>
///     AddMinedCoinToHashflare.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Commands
{
  public class AddMinedCoinToHashflare : ZES.Infrastructure.Domain.Command
  {
    public AddMinedCoinToHashflare() 
    {
    }  
    public string Type
    {
       get; 
       set;
    }  
    public double Quantity
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return "Hashflare";
      }
    }  
    public AddMinedCoinToHashflare(string type, double quantity) 
    {
      Type = type; 
      Quantity = quantity;
    }
  }
}

