/// <filename>
///     AddMinedCoinToHashflareHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Commands
{
  public class AddMinedCoinToHashflareHandler : ZES.Infrastructure.Domain.CommandHandlerBase<AddMinedCoinToHashflare, Hashflare>
  {
    public AddMinedCoinToHashflareHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Hashflare hashflare, AddMinedCoinToHashflare command)
    {
      hashflare.AddAmountMined(command.Type, command.Quantity);
    }
  }
}

