/// <filename>
///     CreateContract.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Commands
{
  public class CreateContract : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public CreateContract() 
    {
    }  
    public string ContractId
    {
       get; 
       set;
    }  
    public string Type
    {
       get; 
       set;
    }  
    public int Quantity
    {
       get; 
       set;
    }  
    public double Total
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return ContractId;
      }
    }  
    public CreateContract(string contractId, string type, int quantity, double total) 
    {
      ContractId = contractId; 
      Type = type; 
      Quantity = quantity; 
      Total = total;
    }
  }
}

