/// <filename>
///     CreateContractHandler.cs
/// </filename>

// <auto-generated/>

using ZES.Interfaces.EventStore;

namespace Chronos.Hashflare.Commands
{
  public class CreateContractHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<CreateContract, Contract>
  {
    public CreateContractHandler(IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Contract Create (CreateContract command)
    {
      return new Contract(command.ContractId, command.Type, command.Quantity, command.Total);
    }
  }
}

