using ZES.Infrastructure.Domain;

// <auto-generated/>
namespace Chronos.Hashflare.Commands
{
    /// <inheritdoc />
    public class ExpireContract : Command
    {
        public ExpireContract() { }

        public ExpireContract(string contractId) 
            : base(contractId) 
        {
        }
    }
}
