/// <filename>
///     ExpireContractHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Commands
{
  public class ExpireContractHandler : ZES.Infrastructure.Domain.CommandHandlerBase<ExpireContract, Contract>
  {
    public ExpireContractHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override void Act (Contract contract, ExpireContract command)
    {
      contract.Expire(command.ContractId);
    }
  }
}

