/// <filename>
///     ExpireContract.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Commands
{
  public class ExpireContract : ZES.Infrastructure.Domain.Command
  {
    public ExpireContract() 
    {
    }  
    public string ContractId
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return ContractId;
      }
    }  
    public ExpireContract(string contractId) 
    {
      ContractId = contractId;
    }
  }
}

