/// <filename>
///     RegisterHashflareHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Commands
{
  public class RegisterHashflareHandler : ZES.Infrastructure.Domain.CreateCommandHandlerBase<RegisterHashflare, Hashflare>
  {
    public RegisterHashflareHandler(ZES.Interfaces.Domain.IEsRepository<ZES.Interfaces.Domain.IAggregate> repository) : base(repository) 
    {
    }  
    protected override Hashflare Create (RegisterHashflare command)
    {
      return new Hashflare(command.Target, command.Username);
    }
  }
}

