/// <filename>
///     RegisterHashflare.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Commands
{
  public class RegisterHashflare : ZES.Infrastructure.Domain.Command, ZES.Interfaces.Domain.ICreateCommand
  {
    public RegisterHashflare() 
    {
    }  
    public string Username
    {
       get; 
       set;
    }  
    public override string Target
    {
       get
      {
        return "Hashflare";
      }
    }  
    public RegisterHashflare(string username) 
    {
      Username = username;
    }
  }
}

