/// <filename>
///     ContractStatsQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Queries
{
  public class ContractStatsQuery : ZES.Infrastructure.Domain.SingleQuery<ContractStats>
  {
    public string ContractId
    {
       get; 
       set;
    }  
    public ContractStatsQuery() 
    {
    }  
    public ContractStatsQuery(string contractId) : base(contractId) 
    {
      ContractId = contractId;
    }
  }
}

