/// <filename>
///     ContractStatsHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Queries
{
  public class ContractStatsHandler : ZES.Interfaces.Domain.IProjectionHandler<ContractStats>
  {
    public ContractStats Handle (ZES.Interfaces.IEvent e, ContractStats state)
    {
      return Handle((dynamic) e, state);
    }  
    public ContractStats Handle (Chronos.Hashflare.Events.ContractCreated e, ContractStats state)
    {
      state.ContractId = e.ContractId; 
        state.Type = e.Type;
      state.Date = e.Timestamp;
      state.Quantity = e.Quantity;
      state.Cost = e.Total;
      state.Mined = 0.0;
      return state;
    }  
    public ContractStats Handle (Chronos.Hashflare.Events.CoinMinedByContract e, ContractStats state)
    {
      return new ContractStats
      {
        ContractId = state.ContractId,
        Type = state.Type,
        Mined = state.Mined + e.Quantity,
        Quantity = state.Quantity,
        Date = state.Date,
        Cost = state.Cost
      };
    }
  }
}