/// <filename>
///     ContractStats.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Queries
{
  public class ContractStats : ZES.Interfaces.Domain.ISingleState
  {
    public ContractStats() 
    {
    }  
    public string ContractId
    {
       get; 
       set;
    }  
    public string Type
    {
       get; 
       set;
    }  
    public double Mined
    {
       get; 
       set;
    }  
    public ContractStats(string contractId, string type, double mined) 
    {
      ContractId = contractId; 
      Type = type; 
      Mined = mined;
    }
  }
}

