/// <filename>
///     HashflareStatsQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Hashflare.Queries
{
  public class HashflareStatsQuery : ZES.Infrastructure.Domain.Query<HashflareStats>
  {
    public HashflareStatsQuery() 
    {
    }
  }
}

