/// <filename>
///     AssetPairInfo.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetPairInfo : ZES.Interfaces.Domain.ISingleState
  {
    public AssetPairInfo()
    {
        QuoteDates = new NodaTime.Instant[0];
    }  
    public Core.Asset ForAsset
    {
       get; 
       set;
    }  
    public Core.Asset DomAsset
    {
       get; 
       set;
    }  
    public NodaTime.Instant[] QuoteDates
    {
       get; 
       set;
    }  
    public AssetPairInfo(Core.Asset forAsset, Core.Asset domAsset, NodaTime.Instant[] quoteDates) 
    {
      ForAsset = forAsset; 
      DomAsset = domAsset; 
      QuoteDates = quoteDates;
    }
  }
}

