/// <filename>
///     GenericAssetPriceHandler.cs
/// </filename>

// <auto-generated/>

using System;
using System.Linq;
using System.Reactive.Linq;
using System.Threading.Tasks;
using Chronos.Core.Commands;
using ZES.Infrastructure;
using ZES.Infrastructure.Domain;
using ZES.Interfaces.Branching;
using ZES.Interfaces.Clocks;
using ZES.Interfaces.Domain;
using ZES.Interfaces.Infrastructure;

namespace Chronos.Core.Queries
{
  [Transient]
  public class AssetQuoteHandler(
    IProjectionManager manager,
    ITimeline activeTimeline,
    ILog log,
    IBranchManager branchManager,
    IClock clock,
    IQueryHandler<AssetPairInfoQuery, AssetPairInfo> pairInfoHandler,
    IQueryHandler<SingleAssetQuoteQuery, SingleAssetQuote> handler,
    ICommandHandler<RetroactiveCommand<UpdateQuote>> updateQuoteHandler,
    IFlowCompletionService completionService)
    : QueryHandlerBase<AssetQuoteQuery, AssetQuote, AssetPairsInfo>(manager, activeTimeline)
  {
    protected override async Task<AssetQuote> Handle(IProjection<AssetPairsInfo> projection, AssetQuoteQuery query)
    {
      var price = 1.0;
      var fordom = AssetPair.Fordom(query.ForAsset, query.DomAsset);
      var info = projection.State;
      info.Tree.Log = log;
      var timestamp = query.Timestamp;
      if (query.Timeline != "")
        timestamp = branchManager.GetTime(query.Timeline);
      else if (timestamp == default)
        timestamp = branchManager.GetTime(branchManager.ActiveBranch);
      
      if (info.Pairs.ToList().Contains(fordom))
      {
        if (query.QueryNet)
        {
          var quoteDates = await pairInfoHandler.Handle(new AssetPairInfoQuery(fordom));
          if (quoteDates.QuoteDates.Where(d => d <= timestamp.ToInstant()).All(d => d.Minus(timestamp.ToInstant()).Days != 0))
          {
            await completionService.RetroactiveExecution.FirstOrDefaultAsync(b => b == false);
            await updateQuoteHandler.Handle(
              new RetroactiveCommand<UpdateQuote>(new UpdateQuote(fordom) { Ephemeral = true }, query.Timestamp));
          }
        }
        
        var result = await handler.Handle(new SingleAssetQuoteQuery(fordom)
        {
          Timeline = query.Timeline,
          Timestamp = query.Timestamp,
        });

        if (result == null || timestamp.ToInstant().Minus(result.Timestamp).Days > 0)
        {
          log.Error($"Stale pricing date for {fordom}");
          return new AssetQuote(new Quantity(0.0, query.DomAsset), timestamp.ToInstant());
        }

        price = result.Price;
      }
      else 
      {
        // try to triangulate the price
        var path = info.Tree.GetPath(query.ForAsset, query.DomAsset);
        if (path == null)
          throw new InvalidOperationException($"No path found from {query.ForAsset?.AssetId} to {query.DomAsset?.AssetId}");

        foreach (var (forAsset, domAsset) in path)
        {
          var pathForDom = AssetPair.Fordom(forAsset, domAsset);
          var isInverse = info.Pairs.Contains(AssetPair.Fordom(domAsset, forAsset));
          if (isInverse)
            pathForDom = AssetPair.Fordom(domAsset,forAsset);

          if (query.QueryNet)
          {
            var quoteDates = await pairInfoHandler.Handle(new AssetPairInfoQuery(pathForDom));
            var now = clock.GetCurrentInstant();
            var intraday = query.Timestamp.ToInstant().InUtc().Date == now.ToInstant().InUtc().Date;
            if (intraday || quoteDates.QuoteDates.Where(d => d <= timestamp.ToInstant()).All(d => timestamp.ToInstant().Minus(d).Days > 0))
            {
              await completionService.RetroactiveExecution.FirstOrDefaultAsync(b => b == false);
              await updateQuoteHandler.Handle(
                new RetroactiveCommand<UpdateQuote>(new UpdateQuote(pathForDom) { Ephemeral = true }, query.Timestamp));
            }
          }
          
          var pathResult = await handler.Handle(new SingleAssetQuoteQuery(pathForDom)
          {
            Timeline = query.Timeline,
            Timestamp = query.Timestamp,
          });
          var pathPrice = pathResult?.Price ?? 1.0;

          if (pathResult == null || timestamp.ToInstant().Minus(pathResult.Timestamp).Days > 0)
          { 
            log.Error($"Stale pricing date for {fordom}");
            pathPrice = 0.0;
          }
          else if (isInverse)
            pathPrice = 1.0 / pathPrice;
          
          price *= pathPrice;
        }
      }
      
      return new AssetQuote(new Quantity(price, query.DomAsset), timestamp.ToInstant()); 
    }
  }
}

