/// <filename>
///     GenericAssetPriceHandler.cs
/// </filename>

// <auto-generated/>

using System;
using System.Linq;
using System.Threading.Tasks;
using ZES.Infrastructure;
using ZES.Infrastructure.Domain;
using ZES.Interfaces.Branching;
using ZES.Interfaces.Domain;
using ZES.Interfaces.Infrastructure;

namespace Chronos.Core.Queries
{
  [Transient]
  public class AssetQuoteHandler : QueryHandlerBase<AssetQuoteQuery, AssetQuote, AssetPairsInfo>
  {
    private readonly IQueryHandler<SingleAssetQuoteQuery, SingleAssetQuote> _handler;
    private readonly ILog _log;
    private readonly IBranchManager _branchManager;

    public AssetQuoteHandler(IProjectionManager manager, ITimeline activeTimeline, ILog log, IBranchManager branchManager, IQueryHandler<SingleAssetQuoteQuery, SingleAssetQuote> handler) 
      : base(manager, activeTimeline)
    {
      _log = log;
      _branchManager = branchManager;
      _handler = handler;
    }

    protected override async Task<AssetQuote> Handle(IProjection<AssetPairsInfo> projection, AssetQuoteQuery query)
    {
      var price = 1.0;
      var fordom = AssetPair.Fordom(query.ForAsset, query.DomAsset);
      var info = projection.State;
      info.Tree.Log = _log;
      var timestamp = query.Timestamp;
      if (query.Timeline != "")
        timestamp = _branchManager.GetTime(query.Timeline);
      else if (timestamp == default)
        timestamp = _branchManager.GetTime(_branchManager.ActiveBranch);
     
      if (info.Pairs.ToList().Contains(fordom))
      {
        var result = await _handler.Handle(new SingleAssetQuoteQuery(fordom)
        {
          Timeline = query.Timeline,
          Timestamp = query.Timestamp,
        });
        
        if (result == null || result.Timestamp.Minus(timestamp.ToInstant()).Days > 0 || timestamp.ToInstant().Minus(result.Timestamp).Days > 0)
          throw new InvalidOperationException($"Stale pricing date for {fordom}");
        price = result.Price;
      }
      else 
      {
        // try to triangulate the price
        var path = info.Tree.GetPath(query.ForAsset, query.DomAsset);
        if (path == null)
          throw new InvalidOperationException($"No path found from {query.ForAsset?.AssetId} to {query.DomAsset?.AssetId}");

        foreach (var (forAsset, domAsset) in path)
        {
          var pathForDom = AssetPair.Fordom(forAsset, domAsset);
          var isInverse = info.Pairs.Contains(AssetPair.Fordom(domAsset, forAsset));
          if (isInverse)
            pathForDom = AssetPair.Fordom(domAsset,forAsset);

          var pathResult = await _handler.Handle(new SingleAssetQuoteQuery(pathForDom)
          {
            Timeline = query.Timeline,
            Timestamp = query.Timestamp,
          });

          if (pathResult == null || pathResult.Timestamp.Minus(timestamp.ToInstant()).Days > 0 || timestamp.ToInstant().Minus(pathResult.Timestamp).Days > 0)
            throw new InvalidOperationException($"Stale pricing date for {pathForDom}");

          if (isInverse)
            pathResult.Price = 1.0 / pathResult.Price;
          
          price *= pathResult.Price;
        }
      }
      
      return new AssetQuote(new Quantity(price, query.DomAsset), timestamp.ToInstant()); 
    }
  }
}

