/// <filename>
///     AssetPrice.cs
/// </filename>

// <auto-generated/>

using System.Collections.Generic;
using ZES.Interfaces.Clocks;
using ZES.Interfaces.Domain;

namespace Chronos.Core.Queries
{
  public class AssetQuote : IHistoricalResults<AssetQuote>
  {
    public AssetQuote() 
    {
    }  
    public Quantity Quantity
    {
       get; 
       set;
    }  
    public NodaTime.Instant Timestamp
    {
       get; 
       set;
    }  
    public AssetQuote(Quantity quantity, NodaTime.Instant timestamp) 
    {
      Quantity = quantity; 
      Timestamp = timestamp;
    }

    public Dictionary<Time, AssetQuote> HistoricalResults { get; } = new();
  }
}

