/// <filename>
///     AssetPairsInfo.cs
/// </filename>

// <auto-generated/>

using System.Linq;

namespace Chronos.Core.Queries
{
  public class AssetPairsInfo : ZES.Interfaces.Domain.IState
  {
    public AssetPairsInfo()
    {
        Tree = new AssetTree();
        Assets = Tree.Assets.ToArray();
        Pairs = new string[0];
    }  
    public Asset[] Assets
    {
       get; 
       set;
    }  
    public string[] Pairs
    {
       get; 
       set;
    }  
    public AssetTree Tree
    {
       get; 
       set;
    }  
    public AssetPairsInfo(Asset[] assets, string[] pairs, AssetTree tree) 
    {
      Assets = assets; 
      Pairs = pairs; 
      Tree = tree;
    }
  }
}

