/// <filename>
///     AssetPrice.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetPrice : ZES.Interfaces.Domain.ISingleState
  {
    public AssetPrice() 
    {
    }  
    public Chronos.Core.Quantity Price
    {
       get; 
       set;
    }  
    public AssetPrice(Chronos.Core.Quantity price) 
    {
      Price = price;
    }
  }
}

