/// <filename>
///     AssetPairsInfoQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetPairsInfoQuery : ZES.Infrastructure.Domain.Query<AssetPairsInfo>
  {
    public AssetPairsInfoQuery() 
    {
    }
  }
}

