/// <filename>
///     GenericAssetPriceQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetPriceQuery : ZES.Infrastructure.Domain.Query<AssetPrice>
  {
    public Chronos.Core.Asset ForAsset
    {
       get; 
       set;
    }  
    public Chronos.Core.Asset DomAsset
    {
       get; 
       set;
    }  
    public AssetPriceQuery() 
    {
    }  
    public AssetPriceQuery(Chronos.Core.Asset forAsset, Chronos.Core.Asset domAsset) 
    {
      ForAsset = forAsset; 
      DomAsset = domAsset;
    }
  }
}

