/// <filename>
///     AssetPairInfoQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetPairInfoQuery : ZES.Infrastructure.Domain.SingleQuery<AssetPairInfo>
  {
    public string Fordom
    {
       get; 
       set;
    }  
    public AssetPairInfoQuery() 
    {
    }  
    public AssetPairInfoQuery(string fordom) : base(fordom) 
    {
      Fordom = fordom;
    }
  }
}

