/// <filename>
///     AssetPrice.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetPrice : ZES.Interfaces.Domain.IState
  {
    public AssetPrice() 
    {
    }  
    public double Price
    {
       get; 
       set;
    }  
    public NodaTime.Instant Timestamp
    {
       get; 
       set;
    }  
    public AssetPrice(double price, NodaTime.Instant timestamp) 
    {
      Price = price; 
      Timestamp = timestamp;
    }
  }
}

