/// <filename>
///     AssetPrice.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetQuote : ZES.Interfaces.Domain.IState
  {
    public AssetQuote() 
    {
    }  
    public Quantity Quantity
    {
       get; 
       set;
    }  
    public NodaTime.Instant Timestamp
    {
       get; 
       set;
    }  
    public AssetQuote(Quantity quantity, NodaTime.Instant timestamp) 
    {
      Quantity = quantity; 
      Timestamp = timestamp;
    }
  }
}

