/// <filename>
///     AssetPairsInfo.cs
/// </filename>

// <auto-generated/>

using System.Collections.Generic;
using System.Linq;

namespace Chronos.Core.Queries
{
  public class AssetPairsInfo : ZES.Interfaces.Domain.IState
  {
    public AssetPairsInfo()
    {
        Tree = new AssetTree();
        Assets = Tree.Assets.ToArray();
        Pairs = [];
    }  
    public Asset[] Assets
    {
       get; 
       set;
    }  
    public string[] Pairs
    {
       get; 
       set;
    }  
    public AssetTree Tree
    {
       get; 
       set;
    }  
    public AssetPairsInfo(Asset[] assets, string[] pairs, AssetTree tree) 
    {
      Assets = assets; 
      Pairs = pairs; 
      Tree = tree;
    }

    public IEnumerable<(Asset ForAsset, Asset DomAsset)> GetPrecedents(Asset forAsset, Asset domAsset)
    {
        var path = Tree.GetPath(forAsset, domAsset);
        var precedents = path?.Select(p => Pairs.Contains(AssetPair.Fordom(p.DomAsset, p.ForAsset)) ? (p.DomAsset, p.ForAsset) : (p.ForAsset, p.DomAsset));
        return precedents;
    }
  }
}