/// <filename>
///     AssetPairInfoHandler.cs
/// </filename>

// <auto-generated/>

using System.Collections.Generic;
using System.Linq;
using NodaTime;

namespace Chronos.Core.Queries
{
  public class AssetPairInfoHandler : ZES.Interfaces.Domain.IProjectionHandler<AssetPairInfo>
  {
    public AssetPairInfo Handle (ZES.Interfaces.IEvent e, AssetPairInfo state)
    {
      return Handle((dynamic) e, state);
    }  
    public AssetPairInfo Handle (Chronos.Core.Events.AssetPairRegistered e, AssetPairInfo state)
    {
      state.ForAsset = e.ForAsset; 
      state.DomAsset = e.DomAsset; 
      return state;
    }  
    public AssetPairInfo Handle (Chronos.Core.Events.QuoteAdded e, AssetPairInfo state)
    {
      var dates = new HashSet<Instant>(state.QuoteDates) {e.Date};
      var newState = new AssetPairInfo(state.ForAsset, state.DomAsset, dates.ToArray());
      return newState;
    }
  }
}

