/// <filename>
///     AssetPairsInfo.cs
/// </filename>

// <auto-generated/>

using System;
using System.Collections.Generic;
using System.Linq;

namespace Chronos.Core.Queries
{
  public class AssetPairsInfo : ZES.Interfaces.Domain.IState
  {
    public AssetPairsInfo() 
    {
    }

    public string[] Pairs { get; set; } = new string[0];
    
    public AssetTree Tree { get; } = new AssetTree();
    
    public AssetPairsInfo(string[] pairs, AssetTree tree)
    {
      Pairs = pairs;
      Tree = tree;
    }

    void Add(Asset forAsset, Asset domAsset)
    {
      var pairs = new HashSet<string> { AssetPair.Fordom(forAsset, domAsset) };
      Pairs = pairs.ToArray();
      Tree.Add(forAsset, domAsset);
    }
  }
}

