/// <filename>
///     GenericAssetPrice.cs
/// </filename>

// <auto-generated/>

namespace Chronos.Core.Queries
{
  public class AssetPrice : ZES.Interfaces.Domain.IState
  {
    public AssetPrice() 
    {
    }  
    public double Price
    {
      get; 
      set;
    }  
    public AssetPrice(double price) 
    {
      Price = price;
    }
  }
}

