/// <filename>
///     GenericAssetPriceQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Core.Queries
{
  public class AssetQuoteQuery : ZES.Infrastructure.Domain.Query<AssetQuote>
  {
    public Chronos.Core.Asset ForAsset
    {
       get; 
       set;
    }  
    public Chronos.Core.Asset DomAsset
    {
       get; 
       set;
    }  
    public AssetQuoteQuery() 
    {
    }  
    
    public bool UpdateQuote { get; set; }
    public bool EnforceCache { get; set; }
    
    public AssetQuoteQuery(Chronos.Core.Asset forAsset, Chronos.Core.Asset domAsset) 
    {
      ForAsset = forAsset; 
      DomAsset = domAsset;
    }
  }
}

