/// <filename>
///     GenericAssetPrice.cs
/// </filename>

// <auto-generated/>

namespace Chronos.Core.Queries
{
  public class GenericAssetPrice : ZES.Interfaces.Domain.IState
  {
    public GenericAssetPrice() 
    {
    }  
    public double Price
    {
      get; 
      set;
    }  
    public GenericAssetPrice(double price) 
    {
      Price = price;
    }
  }
}

