/// <filename>
///     AssetPrice.cs
/// </filename>

// <auto-generated/>

using NodaTime;
using ZES.Infrastructure.Utils;

namespace Chronos.Core.Queries
{
  public class SingleAssetQuote : ZES.Interfaces.Domain.ISingleState
  {
    public SingleAssetQuote() 
    {
    }  
    public double Price
    {
       get; 
       set;
    }  
    public Instant Timestamp
    {
       get; 
       set;
    }  
    public SingleAssetQuote(double price, Instant timestamp) 
    {
      Price = price; 
      Timestamp = timestamp;
    }
    
    public bool IsValid(Instant currentTimestamp, int workingDays = 0) => !double.IsNaN(Price) && Timestamp.IsWithinPriorWorkingDays(currentTimestamp, workingDays);
  }
}

