/// <filename>
///     AssetPriceHandler.cs
/// </filename>

// <auto-generated/>

using NodaTime;

namespace Chronos.Core.Queries
{
  public class SingleAssetQuoteHandler : ZES.Interfaces.Domain.IProjectionHandler<SingleAssetQuote>
  {
    public SingleAssetQuote Handle (ZES.Interfaces.IEvent e, SingleAssetQuote state)
    {
      return Handle((dynamic) e, state);;
    }

    public SingleAssetQuote Handle(Chronos.Core.Events.AssetPairRegistered e, SingleAssetQuote state)
    {
      return new SingleAssetQuote(0.0, Instant.MinValue);
    }
    
    public SingleAssetQuote Handle (Chronos.Core.Events.QuoteAdded e, SingleAssetQuote state)
    {
      return new SingleAssetQuote(e.Close, e.Timestamp.ToInstant());
    }
  }
}

