/// <filename>
///     AssetPriceHandler.cs
/// </filename>

// <auto-generated/>

using NodaTime;
using ZES.Infrastructure.Utils;

namespace Chronos.Core.Queries
{
  public class SingleAssetQuoteHandler : ZES.Interfaces.Domain.IProjectionHandler<SingleAssetQuote>
  {
    public SingleAssetQuote Handle (ZES.Interfaces.IEvent e, SingleAssetQuote state)
    {
      return Handle((dynamic) e, state);;
    }

    public SingleAssetQuote Handle(Chronos.Core.Events.AssetPairRegistered e, SingleAssetQuote state)
    {
      return state.Timestamp == default ? new SingleAssetQuote(double.NaN, Instant.MinValue) : state;
    }
    
    public SingleAssetQuote Handle (Chronos.Core.Events.QuoteAdded e, SingleAssetQuote state)
    {
      return e.Timestamp >= state.Timestamp.ToTime() ? new SingleAssetQuote(e.Close, e.Timestamp.ToInstant(), e.IsFallback) : state;
    }
  }
}

