/// <filename>
///     TransactionInfo.cs
/// </filename>

// <auto-generated/>


using System.Collections.Generic;

namespace Chronos.Core.Queries
{
  public class TransactionInfo : ZES.Interfaces.Domain.ISingleState
  {
    public TransactionInfo() 
    {
    }

    public HashSet<Quantity> Quotes { get; set; } = new HashSet<Quantity>();

    public string TxId
    {
       get; 
       set;
    }  
    public NodaTime.Instant Date
    {
       get; 
       set;
    }  
    public Quantity Quantity
    {
       get; 
       set;
    }  
    public Transaction.TransactionType TransactionType
    {
       get; 
       set;
    }  
    public string Comment
    {
       get; 
       set;
    }  
    public TransactionInfo(string txId, NodaTime.Instant date, Quantity quantity, Transaction.TransactionType transactionType, string comment) 
    {
      TxId = txId; 
      Date = date; 
      Quantity = quantity; 
      TransactionType = transactionType; 
      Comment = comment;
    }
  }
}

