/// <filename>
///     AccountStatsQuery.cs
/// </filename>

// <auto-generated/>

using Chronos.Core;

namespace Chronos.Accounts.Queries
{
  public class AccountStatsQuery : ZES.Infrastructure.Domain.Query<AccountStats>
  {
    public string Name
    {
       get; 
       set;
    }  
    public Asset Denominator
    {
       get; 
       set;
    }

    public bool ConvertToDenominatorAtTxDate { get; set; } = true;
    
    public bool QueryNet { get; set; }
    
    public bool ComputeIrr { get; set; } = true;
    
    public bool IgnoreStale { get; set; }
    
    public AccountStatsQuery() 
    {
    }  
    public AccountStatsQuery(string name, Chronos.Core.Asset denominator) 
    {
      Name = name; 
      Denominator = denominator;
    }
  }
}

