/// <filename>
///     AccountStatsQueryHandler.cs
/// </filename>

// <auto-generated/>

using Chronos.Accounts.Events;

namespace Chronos.Accounts.Queries
{
  public class AccountStatsHandler : ZES.Interfaces.Domain.IProjectionHandler<AccountStatsState>
  {
    public AccountStatsState Handle (ZES.Interfaces.IEvent e, AccountStatsState state)
    {
      return Handle((dynamic) e, state);;
    }  
    public AccountStatsState Handle (Chronos.Accounts.Events.AssetDeposited e, AccountStatsState state)
    {
      var newState = new AccountStatsState(state);
      newState.Add(e.Quantity.Denominator, e.Quantity.Amount);
      return newState;
    }
  }
}

