/// <filename>
///     AccountStats.cs
/// </filename>

// <auto-generated/>

using System.Collections.Generic;
using Chronos.Core;

namespace Chronos.Accounts.Queries
{
  public class AccountStats
  {
    public AccountStats() 
    {
    }  
    public Chronos.Core.Quantity Balance
    {
       get; 
       set;
    }  
    public List<Quantity> Positions { get; set; }
    public List<Quantity> Values { get; set; }
    public List<Quantity> Dividends { get; set; }
    public List<Quantity> CostBasis { get; set; }
    public List<Quantity> RealisedGains { get; set; }
    public Quantity CashBalance { get; set; }
    public Quantity TotalDividend { get; set; }
    
    public AccountStats(Quantity balance) 
    {
      Balance = balance;
    }
  }
}

