/// <filename>
///     AccountStatsQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Queries
{
  public class AccountStatsQuery : ZES.Infrastructure.Domain.SingleQuery<AccountStats>
  {
    public string Name
    {
       get; 
       set;
    }  
    public Chronos.Core.Asset Denominator
    {
       get; 
       set;
    }

    public bool ConvertToDenominatorAtTxDate { get; set; } = false;
    
    public AccountStatsQuery() 
    {
    }  
    public AccountStatsQuery(string name, Chronos.Core.Asset denominator) : base(name) 
    {
      Name = name; 
      Denominator = denominator;
    }
  }
}

