/// <filename>
///     AccountStats.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Queries
{
  public class AccountStats : ZES.Interfaces.Domain.ISingleState
  {
    public AccountStats() 
    {
    }  
    public Chronos.Core.Quantity Balance
    {
       get; 
       set;
    }  
    public AccountStats(Chronos.Core.Quantity balance) 
    {
      Balance = balance;
    }
  }
}

