/// <filename>
///     AccountStatsQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Queries
{
  public class AccountStatsQuery : ZES.Infrastructure.Domain.Query<AccountStats>
  {
    public AccountStatsQuery() 
    {
    }
  }
}

