/// <filename>
///     AccountStatsHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Queries
{
  public class AccountStatsHandler : ZES.Interfaces.Domain.IProjectionHandler<AccountStats>
  {
    public AccountStats Handle (ZES.Interfaces.IEvent e, AccountStats state)
    {
      return Handle(e as Chronos.Accounts.Events.AccountCreated, state);;
    }  
    public AccountStats Handle (Chronos.Accounts.Events.AccountCreated e, AccountStats state)
    {
      return new AccountStats { NumberOfAccounts = state.NumberOfAccounts + 1 };
    }
  }
}

