/// <filename>
///     Stats.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Queries
{
  public class Stats : ZES.Interfaces.Domain.IState
  {
    public Stats() 
    {
    }  
    public int NumberOfAccounts
    {
       get; 
       set;
    }  
    public Stats(int numberOfAccounts) 
    {
      NumberOfAccounts = numberOfAccounts;
    }
  }
}

