/// <filename>
///     TransactionList.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Queries
{
  public class TransactionListState : ZES.Interfaces.Domain.ISingleState
  {
    public TransactionListState() 
    {
    }

    public string[] TxId
    {
      get;
      set;
    } = [];
    public TransactionListState(string[] txId) 
    {
      TxId = txId;
    }
  }
}

