/// <filename>
///     TransactionListHandler.cs
/// </filename>

// <auto-generated/>

using System.Collections.Generic;
using System.Linq;

namespace Chronos.Accounts.Queries
{
  public class TransactionListHandler : ZES.Interfaces.Domain.IProjectionHandler<TransactionList>
  {
    public TransactionList Handle (ZES.Interfaces.IEvent e, TransactionList state)
    {
      return Handle(e as Chronos.Accounts.Events.TransactionAdded, state);;
    }  
    public TransactionList Handle (Chronos.Accounts.Events.TransactionAdded e, TransactionList state)
    {
      var newState = new TransactionList(new HashSet<string>(state.TxId ?? new string[0]) { e.TxId }.ToArray());
      return newState;
    }
  }
}

