/// <filename>
///     TransactionListHandler.cs
/// </filename>

// <auto-generated/>

using System;
using System.Collections.Generic;
using System.Linq;

namespace Chronos.Accounts.Queries
{
  public class TransactionListHandler : ZES.Interfaces.Domain.IProjectionHandler<TransactionListState>
  {
    public TransactionListState Handle (ZES.Interfaces.IEvent e, TransactionListState state)
    {
      return Handle(e as Chronos.Accounts.Events.TransactionAdded, state);;
    }  
    public TransactionListState Handle (Chronos.Accounts.Events.TransactionAdded e, TransactionListState state)
    {
      var newState = new TransactionListState(new HashSet<string>(state.TxId ?? Array.Empty<string>()) { e.TxId }.ToArray());
      return newState;
    }
  }
}

