/// <filename>
///     TransactionList.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Accounts.Queries
{
  public class TransactionList : ZES.Interfaces.Domain.ISingleState
  {
    public TransactionList() 
    {
    }  
    public string[] TxId
    {
       get; 
       set;
    }  
    public TransactionList(string[] txId) 
    {
      TxId = txId;
    }
  }
}

