/// <filename>
///     CoinInfoQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Queries
{
  public class CoinInfoQuery : ZES.Infrastructure.Domain.SingleQuery<CoinInfo>
  {
    public string Name
    {
       get; 
       set;
    }  
    public CoinInfoQuery() 
    {
    }  
    public CoinInfoQuery(string name) : base(name) 
    {
      Name = name;
    }
  }
}

