/// <filename>
///     CoinInfoHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Queries
{
  public class CoinInfoHandler : ZES.Interfaces.Domain.IProjectionHandler<CoinInfo,Chronos.Coins.Events.CoinCreated>
  {
    public CoinInfo Handle (ZES.Interfaces.IEvent e, CoinInfo state)
    {
      return Handle(e as Chronos.Coins.Events.CoinCreated, state);;
    }  
    public CoinInfo Handle (Chronos.Coins.Events.CoinCreated e, CoinInfo state)
    {
      state.Name = e.Name; 
      state.Ticker = e.Ticker; 
      return state;
    }
  }
}

