/// <filename>
///     CoinInfo.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Queries
{
  public class CoinInfo : ZES.Interfaces.Domain.ISingleState
  {
    public CoinInfo() 
    {
    }  
    public string Name
    {
       get; 
       set;
    }  
    public string Ticker
    {
       get; 
       set;
    }  
    public Core.Asset Asset
    {
       get; 
       set;
    }  
    public CoinInfo(string name, string ticker, Core.Asset asset) 
    {
      Name = name; 
      Ticker = ticker; 
      Asset = asset;
    }
  }
}

