/// <filename>
///     StatsHandler.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Queries
{
  public class StatsHandler : ZES.Interfaces.Domain.IProjectionHandler<Stats>
  {
    public Stats Handle (ZES.Interfaces.IEvent e, Stats state)
    {
      return Handle(e as Chronos.Coins.Events.CoinCreated, state);;
    }  
    public Stats Handle (Chronos.Coins.Events.CoinCreated e, Stats state)
    {
      return new Stats { NumberOfCoins = state.NumberOfCoins + 1 };
    }
  }
}

