/// <filename>
///     Stats.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Queries
{
  public class Stats : ZES.Interfaces.Domain.IState
  {
    public Stats() 
    {
    }  
    public int NumberOfCoins
    {
       get; 
       set;
    }  
    public Stats(int numberOfCoins) 
    {
      NumberOfCoins = numberOfCoins;
    }
  }
}

