/// <filename>
///     StatsQuery.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Queries
{
  public class StatsQuery : ZES.Infrastructure.Domain.Query<Stats>
  {
    public StatsQuery() 
    {
    }
  }
}

