/// <filename>
///     WalletInfo.cs
/// </filename>

// <auto-generated/>
 namespace Chronos.Coins.Queries
{
  public class WalletInfo : ZES.Interfaces.Domain.ISingleState
  {
    public WalletInfo() 
    {
    }  
    public string Address
    {
       get; 
       set;
    }  
    public Core.Asset Asset
    {
       get; 
       set;
    }  
    public double Balance
    {
       get; 
       set;
    }  
    public double MineQuantity
    {
       get; 
       set;
    }  
    public WalletInfo(string address, Core.Asset asset, double balance, double mineQuantity) 
    {
      Address = address; 
      Asset = asset; 
      Balance = balance; 
      MineQuantity = mineQuantity;
    }
  }
}

