/// <filename>
///     WalletInfoQueryHandler.cs
/// </filename>

// <auto-generated/>

using Chronos.Core;

namespace Chronos.Coins.Queries
{
  public class WalletInfoHandler : ZES.Interfaces.Domain.IProjectionHandler<WalletInfo>
  {
    public WalletInfo Handle (ZES.Interfaces.IEvent e, WalletInfo state)
    {
      return Handle((dynamic) e, state); 
    }  
    public WalletInfo Handle (Chronos.Coins.Events.WalletCreated e, WalletInfo state)
    {
      state.Address = e.Address;
      state.Asset = new Asset(e.Coin, e.Coin, AssetType.Currency);
      return state;
    }  
    public WalletInfo Handle (Chronos.Coins.Events.WalletBalanceChanged e, WalletInfo state)
    {
      return new WalletInfo
      {
        Address = state.Address,
        Asset = state.Asset,
        Balance = state.Balance + e.Delta.Amount,
        MineQuantity = state.MineQuantity,
      };
    }
    public WalletInfo Handle (Chronos.Coins.Events.CoinMined e, WalletInfo state)
    {
      state.MineQuantity += e.MineQuantity.Amount; 
      return state;
    }
  }
}

